---
- name: Create directory
  file:
    path: "{{ app_directory }}"
    state: directory

- name: Stop dokcer-ompose service
  command: docker compose down
  args:
    chdir: "{{ app_directory }}"
  ignore_errors: yes

# - name: Copy Dockerfile
#   template:
#     src: Dockerfile.j2
#     dest: "{{ app_directory }}/Dockerfile"

# - name: Copy app.py
#   copy:
#     src: "{{ playbook_dir }}/setup/files/app.py"
#     dest: "{{ app_directory }}/{{ app_source_file }}"

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"

- name: Start Docker Compose services
  command: docker compose up --build -d
  args:
    chdir: "{{ app_directory }}"
